defaults:
  - base_config
  - _self_
model:
    k: 20
    width: 30
    verbose : True
    iter_num: 30
    learning_rate: 0.1
    anomaly: True
    C_lengthscale: 50

data:
  name: "DDoS2019"
  time_idx: "Timestamp"
  freq : "S"
  init_len :  240
  categorical_idxs : ["Protocol", "Source IP", "Destination IP"]
  continuous_idxs: ["Flow Duration", "Total Length of Fwd Packets",  "Fwd Header Length", "ACK Flag Count", "Flow Bytes/s", "Flow Packets/s"]
  src_ip_idx: "Source IP"
  dst_ip_idx: "Destination IP"
  label_col: "Label"
  time_scale: 0.003
