defaults:
  - base_config # base config
  - _self_
model:
    k: 20
    width: 30
    verbose : True
    iter_num: 30
    learning_rate: 0.1
    anomaly: True
    C_lengthscale: 30
data:
  name: "Edge"
  time_idx: "frame.time"
  freq : "s"
  init_len :  1200
  categorical_idxs : ["tcp.srcport", "tcp.dstport", "ip.src_host", "ip.dst_host", "tcp.flags", "mqtt.protoname"]
  continuous_idxs: ["tcp.len"]
  label_col: "Attack_type"
  time_scale: 1e-3
