defaults:
  - base_config # base config
  - _self_
model:
    k: 20
    width: 30
    verbose : True
    iter_num: 20
    learning_rate: 0.1
    anomaly: True
    C_lengthscale: 100
data:
  name: "WebIDS2023"
  time_idx: "ts"
  freq : "S"
  init_len :  300
  # categorical_idxs : ["Dst Port", "Protocol"]
  categorical_idxs : ["id.orig_h", "id.resp_h", "service", "traffic_direction"]
  # continuous_idxs: ["flow_duration", "fwd_pkts_per_sec",  "bwd_pkts_per_sec", "flow_FIN_flag_count", "flow_SYN_flag_count", "flow_RST_flag_count", "flow_ACK_flag_count", "fwd_PSH_flag_count", "bwd_PSH_flag_count", "payload_bytes_per_second"]
  continuous_idxs: ["fwd_pkts_per_sec",  "bwd_pkts_per_sec",  "payload_bytes_per_second"]
  label_col: "attack_type"
  time_scale: 3e-4
  src_ip_idx: "id.orig_h"
  dst_ip_idx: "id.resp_h"
